name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure Node.js v18 or higher is used

    - name: Build assets
      run: |
        rm -rf node_modules # Remove existing node_modules to avoid platform conflicts
        npm install
        npm run build

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    # The remote directory on the server

    # Optional: Clean up files on the server if necessary
    # - name: Clean up old files on the server
    #   run: ssh username@hostname 'rm -rf /public_html/old_files'
